navikt/min-side-arbeidsgiver

- .circleci/config.yml
- Dockerfile
- src/App/App.tsx
- src/api/dnaApi.ts
- src/server/server.js
- src/server/sonekrysningConfig.js
- start.sh
- tsconfig.json
- yarn.lock
Bygger nå frontenden utenfor dockerimaget og kopierer buildmappa inn i imaget etterpå.
Da går bygget raskere på CircleCI.
Nå feiler ikke frontenden heller hvis man får en feilmelding fra APIet.
> Tag 329 Forbedre bygg på CircleCI

- nais-preprod.yaml
- src/App/Hovedside/AltinnContainer/AltinnContainer.less
- src/App/Hovedside/Hovedside.less
- src/App/Hovedside/NyttigForDegContainer/NyttigForDegContainer.less
- src/App/Hovedside/TjenesteBoksContainer/TjenesteBoksContainer.less
fikset så dropdownen ser ok ut for mobil, og støtte til iphone 4
> fikset så appen støtter iphone 4

- LICENSE.md
> Legg til LICENSE.md

- src/App/Hovedside/TjenesteBoksContainer/Arbeidstreningboks/Arbeidstreningboks.tsx
*forenkler komponenten en del
*viser kun oppsumering av antall arbeidstaler med en type status, ser antall > 0
> Tag 709 vis arbeidsavtaler med status

- nais-prod.yaml
- package-lock.json
- package.json
- src/App/HovedBanner/HovedBanner.tsx
- src/App/InformasjonOmTilgangsstyringSide/InformasjonOmTilgangsstyringSide.less
- src/App/InformasjonOmTilgangsstyringSide/InformasjonOmTilgangsstyringSide.tsx
- src/lenker.ts
- yarn.lock
> Tag 899 oppdater tekst painfor om tilgangsstyring siden

- nais-preprod.yaml
- src/App/Hovedside/AltinnContainer/AltinnLenke/AltinnLenke.tsx
- src/App/Hovedside/Hovedside.tsx
- src/App/Hovedside/NyttigForDegContainer/ArbeidsgiverTelefon/ArbeidsgiverTelefon.tsx
- src/App/Hovedside/NyttigForDegContainer/Bedriftsinfoknapp/Bedriftsinfoknapp.tsx
- src/App/Hovedside/NyttigForDegContainer/KontaktOss/KontaktOss.tsx
- src/App/Hovedside/SkjemaveilederContainer/SkjemaveilederContainer.tsx
- src/App/Hovedside/TjenesteBoksContainer/Arbeidstreningboks/Arbeidstreningboks.tsx
- src/App/Hovedside/TjenesteBoksContainer/IAwebboks/IAwebboks.tsx
- src/App/Hovedside/TjenesteBoksContainer/Pamboks/Pamboks.tsx
- src/App/Hovedside/TjenesteBoksContainer/Syfoboks/Syfoboks.tsx
- src/App/Hovedside/TjenesteBoksContainer/TjenesteBoksContainer.tsx
- src/OrganisasjonDetaljerProvider.tsx
mer logging av tilganger og hvor folk klikker
> Tag 921 logge antall klikk

- src/OrganisasjonDetaljerProvider.tsx
- src/OrganisasjonsListeProvider.tsx
Skru på tilsagnsbrev. Testet i dev igjen.
> TAG-1427 Fjerner feature toggle for tilsagnsbrev

- src/utils/funksjonerForAmplitudeLogging.ts
sjekk at info fra ereg ikke er null v amplitudelogging
> fiks feil som oppstår hvis info fra ereg er tom

- src/App/Koronaboks/Koronaboks.tsx
- src/lenker.ts
> Fjerne lenke for lønnskompensasjon

- src/App/InformasjonOmTilgangsstyringSide/InformasjonOmTilgangsstyringSide.tsx
fra informasjonsside om tilgangsstyring
> Tar bort seksjonen: Innmelding for lønnskompensasjon og refusjon

- server/package-lock.json
- server/server.js
vet ikke om dette er noe vi vil ha, men det er ihvertfall en mulighet.
> poll oppdater dekorator

- nais/dev-sbs.json
- nais/labs-gcp.json
- nais/prod-sbs.json
- naiserator.yaml
Har duplisert secrets i vault så det finnes både for default og arbeidsgiver.
> Bruk team namespace

- src/App/Hovedside/BeOmTilgang/SyfoBeOmTilgangModalBoks/SyfoBeOmTilgangModalBoks.tsx
- src/App/Hovedside/SkjemaveilederContainer/SkjemaveilederContainer.tsx
- src/App/Hovedside/TjenesteBoksContainer/Arbeidsforholdboks/Arbeidsforholdboks.tsx
- src/App/Hovedside/TjenesteBoksContainer/Pamboks/Pamboks.tsx
- src/App/Hovedside/TjenesteBoksContainer/Syfoboks/Syfoboks.tsx
- src/App/Hovedside/TjenesteBoksContainer/Tiltakboks/Tiltakboks.tsx
- src/App/InformasjonOmTilgangsstyringSide/InformasjonOmTilgangsstyringSide.tsx
- src/App/Koronaboks/Koronaboks.tsx
- src/api/dnaApi.ts
- src/api/enhetsregisteretApi.ts
- src/api/pamApi.ts
- src/lenker.ts
- src/mock/pamMock.ts
- src/mock/syfoMock.ts
https://jira.adeo.no/browse/TAG-1627
> Lonnskompensasjon lenke

- codegen.yml
- craco.config.js
- nais/dev-sbs.json
- naiserator.yaml
- package.json
- server/server.js
- src/App/App.tsx
- src/App/Hovedside/varsler/Varselpanel/Varselpanel.tsx
- src/App/Hovedside/varsler/Varsler.tsx
- src/App/OrganisasjonDetaljerProvider.tsx
- src/FeatureToggleProvider.tsx
- src/api/bruker.graphql
- src/api/graphql-types.ts
- src/api/graphql.tsx
- src/index.tsx
- src/utils/environment.ts
- yarn.lock
la også til generering av typer basert på importert skjema
> la til apollo graphql client og mock oppsett

- src/App/Hovedside/varsler/Varselpanel/VarselLenkepanel/VarselLenkepanel.tsx
- src/App/Hovedside/varsler/Varsler.tsx
- src/App/Hovedside/varsler/varsler-knapp/VarslerKnapp.tsx
- src/App/OrganisasjonDetaljerProvider.tsx
- src/App/hooks/useLocalStorage.ts
skrudd på long polling i apollo.
Lagrer sist lest notifikasjon til localStorage når bjellen trykkes på.
Viser antall nye, fungerer også når det polles i bakgrunnen.
> Poll notifikasjoner

- src/App/Hovedside/Hovedside.tsx
- src/App/Hovedside/ManglerTilgangContainer/ManglerTilgangContainer.tsx
- src/App/OrganisasjonerOgTilgangerProvider.tsx
- src/mock/syfoMock.ts
- Innfører sjekk på om bruker har tilgang i en underenhet, hvis ikke vises "mangler tilganger" 
- Flytter harTilganger ut i context
> Håndter selskap uten underenhet

- server/server.js
- src/index.tsx
- src/utils/environment.ts
https://nav-it.slack.com/archives/CFJEMAQ0Z/p1613486649009200?thread_ts=1613474640.004600&cid=CFJEMAQ0Z
> prøver å fikse cors feil som skjer on load

- package.json
- yarn.lock
> bump notifikasjoner widget

- src/App/Hovedside/AltinnContainer/AltinnContainer.less
- src/App/Hovedside/AltinnContainer/AltinnContainer.tsx
- src/App/Hovedside/AltinnMeldingsboks/BrevFraAltinnContainer.less
- src/App/Hovedside/Hovedside.tsx
- src/App/Hovedside/NyttigForDegContainer/Bedriftsinfoknapp/Bedriftsinfoknapp.less
- src/App/Hovedside/NyttigForDegContainer/Bedriftsinfoknapp/Bedriftsinfoknapp.tsx
- src/App/Hovedside/NyttigForDegContainer/KontaktOss/KontaktOss.less
- src/App/Hovedside/SkjemaveilederContainer/SkjemaveilederContainer.less
endringer iht [designskisse](https://www.figma.com/file/YS45RBAyyckJMqKBpkGq0r/Min-side---arbeidsgiver---tilganger%2C-feilsituasjoner-og-dialog-til-Figma?node-id=2793%3A21980)
* endre rekkefølge på panelgrupper på siden
* juster størrelse på kontakt oss og info om bedrift bokser
> Endre layout

- server/server.js
- src/App/HovedBanner/HovedBanner.tsx
nå som proxyen når bruker-api i prod så kan vi bruke default url i stedet for frackend proxy
> bruk ag-notifikasjon-proxy i stedet for frackend proxy

- package.json
- src/App/HovedBanner/HovedBanner.tsx
- yarn.lock
> bump widget til 1.0.0

- yarn.lock
snyk ville bumpe, ser at ny versjon dropper cookies til andre domener og ville sjekke at ting virker som det skal i dev. Det gjør det.
> bump follow-redirect

- src/utils/amplitude.ts
jf. https://nav-it.slack.com/archives/CMK1SCBP1/p1643188503009500
> Oppdater endepunkt for amplitude

- src/App/App.less
- src/App/InformasjonOmTilgangsstyringSide/InformasjonOmTilgangsstyringSide.less
- src/App/InformasjonOmTilgangsstyringSide/InformasjonOmTilgangsstyringSide.tsx
Mangler space før footeren.
Bruker `gap` for å passe på at det er passe med rom mellom elementer.
> Missing gap on tilgangsside

- package-lock.json
- src/App/Hovedside/Sak/Saksoversikt/Saksoversikt.tsx
- src/App/Hovedside/Sak/Saksoversikt/SideBytter/SideBytter.tsx
- src/App/Hovedside/Sak/SisteSaker/SisteSaker.tsx
- src/App/Hovedside/Sak/useSaker.ts
Forsøk på å bruke reducer for å holde styr på ønsket tilstand
> use reduce and filter

- src/App/InformasjonOmTilgangsstyringSide/InformasjonOmTilgangsstyringSide.tsx
denne dukket opp på en annen PR med urelaterte endringer
> supress warnning

- src/App/Hovedside/Sak/SakPanel.tsx
- src/App/Hovedside/Sak/Saksoversikt/Saksoversikt.tsx
- src/App/Hovedside/Sak/SisteSaker/SisteSaker.tsx
- src/App/Hovedside/Sak/useSaker.tsx
> legg til amplitude log for aktivitet relatert saker

- server/mock/syfoMock.js
- src/App/Alerts/Alerts.tsx
- src/App/Hovedside/BeOmTilgang/BeOmTilgang.tsx
- src/App/Hovedside/DigiSyfoBedriftsmenyInfo.less
- src/App/Hovedside/DigiSyfoBedriftsmenyInfo.tsx
- src/App/Hovedside/Hovedside.tsx
- src/App/Hovedside/TjenesteBoksContainer/TjenesteBoksContainer.tsx
- src/App/OrganisasjonerOgTilgangerProvider.tsx
- src/api/dnaApi.ts
- src/lenker.ts
- https://github.com/navikt/min-side-arbeidsgiver-api/pull/246
> Tag 1896, legg til nærmeste leder virksomheter i bedriftsmeny

- src/App/Hovedside/TjenesteBoksContainer/TjenesteBoksContainer.tsx
Har fått en rapport om at virksomhetsmenyen ikke viser
virksomhet man har tilgang i. I stede for a reverte alt, så
henter vi tilbake det viktige.
> Vis tjenesteboks til digisyfo ved global tilgang.

- .github/workflows/bygg-og-deploy-master.yml
https://www.githubstatus.com/incidents/6r4sms3hcj3x
> reenable cache, kan merges når gh er i vater igjen

- craco.config.js
- server/mock/refusjonsStatusMock.js
- server/server.js
- src/App/Hovedside/TjenesteBoksContainer/TjenesteBoksContainer.tsx
- src/App/InformasjonOmTilgangsstyringSide/InformasjonOmTilgangsstyringSide.tsx
- src/App/OrganisasjonerOgTilgangerProvider.tsx
- src/FeatureToggleProvider.tsx
- src/api/dnaApi.ts
- src/lenker.ts
> vis tjenesteboks bare dersom virksomhet har tilgang

- src/App/Hovedside/Sak/SakPanel.tsx
ikke log tittel, det kan inneholde personinfo som vi ikke
trenger i amplitude.
> amplitude: logg merkelapp på klikket sak.

- src/App/Hovedside/NyttigForDegContainer/Bedriftsinfoknapp/Bedriftsinfoknapp.tsx
- src/App/Hovedside/Sak/SisteSaker/SisteSaker.tsx
Scroller til toppen når man navigerer til "Saksoversikt" og "Informasjo fra enhetsregistret"
> Scroller til topps

- src/App/InformasjonOmTilgangsstyringSide/InformasjonOmTilgangsstyringSide.tsx
- src/App/InformasjonOmTilgangsstyringSide/PanelerMedInnholdsfortegnelse.tsx
jf. https://nav-it.slack.com/archives/CCNAY9FGF/p1657192612941789
> Beskriv enkeltrettigheten Brev om dialogmøte

- .github/workflows/bygg-branch.yml
- .github/workflows/bygg-og-deploy-master.yml
- .npmrc
- package-lock.json
- package.json
- src/App/Hovedside/KontaktFelt/KontaktFelt.less
- src/App/Hovedside/KontaktFelt/KontaktFelt.tsx
- src/index.tsx
etter at dekoratøren endret oppførsel så sluttet vår åpne lukke funksjon å fungere
oppdaterer til ny versjon der de har eksponert mulighet til å åpne via api.
> fiks chatbot breakage

- src/App/Hovedside/DigiSyfoBedriftsmenyInfo.less
- src/App/Hovedside/DigiSyfoBedriftsmenyInfo.tsx
- src/GeneriskeElementer/Lukknapp.tsx
Knappen er litt større (48x48px), men det er for så vidt minimum WCAG afaik. Følger designsystemets anbefaling for ikon-knapper.
> Fjern lukkeknapp

- src/App/Hovedside/BeOmTilgang/SyfoBeOmTilgangModalBoks/SyfoBeOmTilgangModalBoks.tsx
> bytt til ny modal

- src/App/App.less
- src/App/Hovedside/AltinnMeldingsboks/BrevFraAltinnContainer.less
- src/App/Hovedside/BeOmTilgang/BeOmTilgang.less
- src/App/Hovedside/BeOmTilgang/SyfoBeOmTilgangModalBoks/SyfoBeOmTilgangModalBoks.less
- src/App/Hovedside/BeOmTilgang/TjenesteInfo/TjenesteInfo.less
- src/App/Hovedside/Hovedside.less
- src/App/Hovedside/KontaktFelt/KontaktFelt.less
- src/App/Hovedside/Koronaboks/Koronaboks.less
- src/App/Hovedside/ManglerTilgangContainer/ManglerTilgangContainer.less
- src/App/Hovedside/NyttigForDegContainer/Bedriftsinfoknapp/Bedriftsinfoknapp.less
- src/App/Hovedside/NyttigForDegContainer/NyttigForDegContainer.less
- src/App/Hovedside/Sak/Saksoversikt/Saksoversikt.less
- src/App/Hovedside/Sak/SisteSaker/SisteSaker.less
- src/App/Hovedside/SkjemaveilederContainer/SkjemaveilederContainer.less
- src/App/Hovedside/TjenesteBoksContainer/Pamboks/Pamboks.less
- src/App/Hovedside/TjenesteBoksContainer/Tiltakboks/Tiltakboks.less
- src/App/Hovedside/TjenesteBoksContainer/TjenesteBoksBanner/TjenesteBoksBanner.less
- src/App/Hovedside/TjenesteBoksContainer/TjenesteBoksContainer.less
- src/App/InformasjonOmBedrift/InformasjonOmBedrift.less
- src/App/InformasjonOmBedrift/OverordnetEnhet/OverordnetEnhet.less
- src/App/InformasjonOmBedrift/Underenhet/Underenhet.less
- src/App/InformasjonOmTilgangsstyringSide/InformasjonOmTilgangsstyringSide.less
- src/App/InformasjonOmTilgangsstyringSide/PanelerMedInnholdsfortegnelse.less
- src/App/LoggInn/LoggInnBanner/LoggInnBanner.less
- src/App/LoggInn/Logginn.less
- src/App/LoggInn/TilgangsStyringInfoTekst/TilgangsStyringInfoTekst.less
- src/GeneriskeElementer/AntallUlest.less
Fra det jeg kan se ved å sammeligne labs og experimental labs ser det helt likt ut. Ny versjon er deployet i experimental.
[gammel (labs)](https://arbeidsgiver.labs.nais.io/min-side-arbeidsgiver/?bedrift=999999999) _________________________________________ [ny (experimental)](https://experimental-arbeidsgiver.labs.nais.io/min-side-arbeidsgiver/?bedrift=999999999)
> bytt fra less variabel til css vars

- src/App/Hovedside/Sak/OmSaker.tsx
- src/App/Hovedside/Sak/Saksoversikt/Saksoversikt.tsx
- src/App/Hovedside/Sak/SisteSaker/SisteSaker.tsx
Bruker teksten fra jira-saken. Men legger på mellomrom så det blir "etter hvert".
> ny sak å fortelle om

- server/brukerapi-proxy-middleware.js
- server/server.js
trenger ikke lenger å instrumentere tokenx client
> litt cleanup etter mock middleware tatt i bruk

- nais/dev-gcp.yaml
- nais/prod-gcp.yaml
- server/brukerapi-proxy-middleware.js
- server/server.js
TODO:
- https://github.com/navikt/tiltaksgjennomforing-api/pull/1019
> bruk tokenx på kall til tiltaksgjennomforing-api

- package-lock.json
- package.json
- server/package-lock.json
- server/package.json
Bumpe notifikasjoner til 5.1.0 med frist
> Teste frist i oppgaver widget

- bruker.graphql
- package-lock.json
- package.json
- server/package-lock.json
- server/package.json
- src/App/Hovedside/Sak/SakPanel.tsx
- src/App/Hovedside/Sak/Saksoversikt/Filter.tsx
- src/App/Hovedside/Sak/Saksoversikt/Saksoversikt.css
- src/App/Hovedside/Sak/Saksoversikt/Saksoversikt.tsx
- src/App/Hovedside/Sak/Saksoversikt/useOversiktSessionStorage.ts
- src/App/Hovedside/Sak/Saksoversikt/useOversiktStateTransitions.ts
- src/App/Hovedside/Sak/SisteSaker/SisteSaker.tsx
- src/App/Hovedside/Sak/useSaker.tsx
> brukerstyrt sortering i saksoversikt

- src/App/LoggInn/LoggInn.tsx
- src/App/LoggInn/Logginn.css
> oppdater liste over ting man kan gjøre på MSA

- package-lock.json
- package.json
- server/package-lock.json
- server/package.json
> bump til siste  av notifikasjonswidget

- server/package-lock.json
- server/package.json
dukket opp en bump PR på denne fra dependabot og snyk, men vi bruker det ikke lenger. ble innført ifbm et abtest endepunkt i fjor. se PR #884 commitish 220668b
test:
> fjern ubrukt dependency

- src/App/Alerts/Alerts.tsx
Nye elementer leses opp hvis de legges til. 
Testet lokalt.
> role status on alerts

- server/server.js
TODO:
ref:
- https://jira.adeo.no/browse/TAG-2028
> slett cookie før forward dersom auth bearer settes

- src/App/Hovedside/Sak/Saksfilter/Virksomhetsmeny/Virksomhetsmeny.tsx
- src/App/Hovedside/Sak/Saksoversikt/Saksoversikt.tsx
- src/utils/funksjonerForAmplitudeLogging.ts
- src/utils/util.ts
> Saksoversiktfilter amplitude

- src/api/altinnApi.ts
- src/api/arbeidsavtalerApi.ts
- src/api/dnaApi.ts
- src/api/enhetsregisteretApi.ts
- src/api/pamApi.ts
- src/api/sykefraværStatistikkApi.ts
- src/lenker.ts
* flytt urler fra lenker.ts til der de er brukt
* legg til zod og sentry og bedre feilmelding der det mangler
> litt opprydding i api kall

- package-lock.json
> Bump versjoner

- src/App/LoggInn/VarselOmNedetid/VarselHvisNedetid.tsx
Reverts navikt/min-side-arbeidsgiver#1564
> Revert "remove driftsmelding"

- server/server.js
- src/setupProxy.js
TODO:
---
se også 
- https://github.com/navikt/loginservice/commit/a8b7f320bda8e0f15080a4611f989a78866a2ca2
> redirect til siden brukeren var på før redirect til login

- src/App/Hovedside/BeOmTilgang/BeOmTilgang.tsx
- src/App/InformasjonOmTilgangsstyringSide/InformasjonOmTilgangsstyringSide.tsx
- src/altinn/tjenester.ts
- src/utils/funksjonerForAmplitudeLogging.ts
https://jira.adeo.no/browse/TAG-2052
> Ny tjeneste forebyggefravar

- src/App/Hovedside/Sak/Saksfilter/Saksfilter.tsx
- src/App/Hovedside/Sak/Saksoversikt/Saksoversikt.tsx
- src/App/Hovedside/Sak/Saksoversikt/useOversiktSessionStorage.ts
- src/App/Hovedside/Sak/Saksoversikt/useOversiktStateTransitions.ts
- src/App/Hovedside/Sak/SisteSaker/SisteSaker.css
- src/App/Hovedside/Sak/SisteSaker/SisteSaker.tsx
- src/App/Hovedside/Sak/useSaker.tsx
Reverts navikt/min-side-arbeidsgiver#1584
vi oppdaget at det ikke fungerer. reverter for så å fikse å pushe det ut på nytt
> Revert "Vise saker for alle virksomheter"

- src/App/Hovedside/Sak/Saksfilter/Saksfilter.tsx
- src/App/Hovedside/Sak/Saksoversikt/Saksoversikt.tsx
- src/App/Hovedside/Sak/Saksoversikt/useOversiktSessionStorage.ts
- src/App/Hovedside/Sak/Saksoversikt/useOversiktStateTransitions.ts
- src/App/Hovedside/Sak/SisteSaker/SisteSaker.css
- src/App/Hovedside/Sak/SisteSaker/SisteSaker.tsx
- src/App/Hovedside/Sak/useSaker.tsx
Reverts navikt/min-side-arbeidsgiver#1585
> Revert "Revert "Vise saker for alle virksomheter""

- src/App/Hovedside/Sak/Saksfilter/Virksomhetsmeny/Virksomhetsmeny.tsx
Viser teksten "(Alle valgt)" i virksomhetsvelgeren dersom alle bedrifter er valgt.
> Vise alle valgt i virksomhetsvelgeren

- src/lenker.ts
ref: https://nav-it.slack.com/archives/C01V9FFEHEK/p1680244597180449
> oppdater lenke til kandidatliste i dev

- src/lenker.ts
Fjerner ubrukte lenker.
Fikser labs-lenke til permitterings-skjema.
> fjern ubrukte lenke, fiks labslenke til permitteringssskjema

- package-lock.json
- package.json
- server/package-lock.json
- server/package.json
bump til versjon av widget som filtrerer bort oppgaver som er løst eller utført
* https://github.com/navikt/arbeidsgiver-notifikasjon-widget/pull/151
> Filtere bort løste oppgaver fra antall uleste i bjella

- src/App/Hovedside/Sak/SisteSaker/SisteSaker.tsx
Returnerer null dersom antall saker for alle virksomheter er 0 eller undefined.
> Viser "Se alle saker" så lenge virksomhet har noen sak.

- server/tokenx.js
Skaper ekstremt mange logginnslag, og har begrenset verdi.
> Fjern logg-innslag ved vellykket tokenx

- bruker.graphql
- package-lock.json
- package.json
- server/package-lock.json
- server/package.json
- src/api/graphql-types.ts
Bumpet notifikasjonswidget til 6.2.2
> Tag 2113 sakstittel for notifikasjoner widget

- src/App/App.tsx
Fjerner
```jsx
<Routes>
<Route
path="*"
element={
...
}
/>
</Routes>
```
> remove route no longer needed

- server/mock/sykefraværMock.js
- server/server.js
- src/api/sykefraværStatistikkApi.ts
* https://github.com/navikt/min-side-arbeidsgiver-api/pull/318
> ta i bruk nytt api for sykefraværstatistikk

- nais/dev-gcp.yaml
- nais/prod-gcp.yaml
- server/mock/antallArbeidsforholdMock.js
- server/server.js
- src/App/Hovedside/TjenesteBoksContainer/Arbeidsforholdboks/Arbeidsforholdboks.tsx
- src/api/arbeidsforholdApi.ts
* https://github.com/navikt/arbeidsgiver-innsyn-aareg-api/pull/405
TODO:
> hent antall arbeidsforhold

- server/mock/antallArbeidsforholdMock.js
- server/server.js
- src/api/arbeidsforholdApi.ts
Det fungerer som det var, men litt misvisende.
> fiks express url til proxy

- .github/workflows/bygg-branch.yml
- .github/workflows/bygg-og-deploy-master.yml
todo:
depends on:
* https://github.com/nais/frontend-plattform/pull/87
> bruk cdn til css og js

- server/mock/altinnMeldingsboksMock.js
- server/mock/altinnMock.js
- server/server.js
- src/App/OrganisasjonerOgTilgangerProvider.tsx
- src/altinn/organisasjon.ts
- src/altinn/tilganger.ts
- src/api/dnaApi.ts
- src/index.tsx
Reverts navikt/min-side-arbeidsgiver#1653
> Revert "hent organisasjoner og tilganger fra nytt userinfo endepunkt"

- server/mock/altinnMeldingsboksMock.js
- server/mock/userInfoMock.js
- server/server.js
- src/App/OrganisasjonerOgTilgangerProvider.tsx
- src/altinn/organisasjon.ts
- src/altinn/tilganger.ts
- src/api/dnaApi.ts
- src/index.tsx
Reverts navikt/min-side-arbeidsgiver#1656
> Revert "Revert "hent organisasjoner og tilganger fra nytt userinfo endepunkt""

- .github/workflows/bygg-og-deploy-master.yml
https://docs.sentry.io/product/releases/associate-commits/#using-the-cli
> accosiate commits with release

- nais/experimental-labs-gcp.yaml
- nais/labs-gcp.yaml
- server/mock/innloggetMock.js
The old url is deprecated and will be removed soon.
> chore: update fakedings url

- src/api/altinnApi.ts
altinn sier cors listen er oppdatert hos dem
TODO:
> altinn login redirect i dev

- server/mock/presenterteKandidaterMock.js
- src/App/Hovedside/TjenesteBoksContainer/Kandidatlisteboks/useAntallKandidater.ts
- vite.config.ts
ref: https://swr.vercel.app/docs/error-handling#error-retry
> TBD: eksempel på error handling med retry

- src/App/Hovedside/BeOmTilgang/BeOmTilgang.tsx
Faktisk endring på linje 34:
```typescript jsx
'tilskuddsbrev',
```
resten er prettier.
> Fjern be-om-tiltang for tilskuddsbrev

- vite.config.ts
> vite: generate sourcemaps

- src/App/Hovedside/TjenesteBoksContainer/Arbeidsforholdboks/useAntallArbeidsforholdFraAareg.ts
her kommer det null og ikke som optional.
oppdaterte også til ny stil i hook med retry
> fiks feil i useAntallArbeidsforholdFraAareg

- package-lock.json
- package.json
- server/package-lock.json
- server/package.json
verifisert lokalt:
```
would have sent to sentry: Response not successful: Received status code 401
```
> oppdater widget for å fikse json parse error

- server/mock/varslingStatusMock.js
- server/server.js
- src/App/Alerts/Alerts.tsx
- src/App/Hovedside/Hovedside.tsx
- src/App/useVarslingStatus.ts
- https://github.com/navikt/min-side-arbeidsgiver-api/pull/331
- https://github.com/navikt/arbeidsgiver-notifikasjon-produsent-api/pull/569
> legg til alert for feilede varsler

- src/App/App.tsx
- src/App/Hovedside/NyttigForDegContainer/Bedriftsinfoknapp/Bedriftsinfoknapp.tsx
- src/App/InformasjonOmBedrift/OverordnetEnhet/OverordnetEnhet.tsx
- src/App/InformasjonOmBedrift/Underenhet/Underenhet.tsx
Noen endrigner fra Figma-skissene. Diskuterte det med Hanna for en stund siden, men er jo ikke fremhevet i Jira-tasken at det også er endret.
> Noen endringer for å komme nærmere figma

- server/mock/altinnBeOmTilgangMock.js
- src/altinn/tilganger.ts
typen i apiet er deklarert som Int/number både i min-side-arbeidsgiver-api og altinn https://www.altinn.no/api/serviceowner/Help/Api/GET-serviceowner-delegationRequests_serviceCode_serviceEditionCode_status[0]_status[1]_continuation_coveredby_offeredby
> fiks zod parse error

- src/api/enhetsregisteretApi.ts
- src/utils/funksjonerForAmplitudeLogging.ts
ref: https://sentry.gc.nav.no/organizations/nav/issues/517057/?project=27
> antall ansatte kan være undefined på underenhet

- server/mock/innloggetMock.js
- src/App/LoginBoundary.tsx
- src/App/useUserInfo.ts
- src/api/dnaApi.ts
etter denne er merget og kjørt en stund kan apiet fjernes:
- https://github.com/navikt/min-side-arbeidsgiver-api/pull/341
> sjekk inlogget via useUserInfo

- src/App/LoginBoundary.tsx
Virker som det fortsatt er tilfeller hvor det retries mange ganger før redirect skjer. Kanskje det er noe caching?
> Prioriter 401-sjekk høyest

- server/server.js
reproduseres ved å slette build mappa lokalt
> local dev starter ikke uten at man har kjørt build

- server/server.js
lånt fra https://github.com/helmetjs/nocache/blob/main/index.js
> set no cache headers

- index.html
- ✅  testet i dev
before:
after:
> set strict-origin referrer policy

- src/Pages/Hovedside/Tjenestebokser/TiltakAvtaler/useAvtaleoversikt.ts
> retry kall til tiltaksgjennomforing-api

- server/mock/userInfoMock.js
- src/altinn/organisasjon.ts
> organisasjonform kommer av og til som null i prod

- src/Pages/OrganisasjonerOgTilgangerProvider.tsx
- vite.config.ts
tanken med dette er å kunne se i amplitude hvor mange som har gamle klienter
> legg til build timestamp som userprop i amplitude

- src/Pages/Saksoversikt/SakPanel.tsx
> endrer level på sakpanel fra defaul 1 til 2

- src/Pages/Hovedside/AktueltRubrikk.tsx
https://jira.adeo.no/browse/TAG-2227
> aktuelt om Digital utsending av post vises i 30 dager

- nais/demo-devlik.yaml
- nais/demo-prodlik.yaml
Reverts navikt/min-side-arbeidsgiver#1774
> Revert "fiks ugyldig configs. disse vil feile jf. endring i validering policy…"

- server/package-lock.json
- server/package.json
- server/tokenx.js
https://nav-it.slack.com/archives/C04KJL7L545/p1704991177905499
> 401 for expired tokens i tokenx middleware

- index.html
- package-lock.json
- package.json
- src/index.tsx
dashboard for dev:
https://grafana.nav.cloud.nais.io/d/k8g_nks4z/frontend-web-vitals?orgId=1&var-app=min-side-arbeidsgiver&var-env=P7BE696147D279490&from=now-1h&to=now
> Ta i bruk Faro for observability i web klient

- src/Pages/Hovedside/Hovedside.tsx
- src/Pages/Hovedside/Kalenderavtaler.css
- src/Pages/Hovedside/Kalenderavtaler.tsx
Kalenderkomponenter i hovedsiden er påbegynt. Sted benyttes ikke i henhold til skisser for dialogmøter. Det må implementeres dersom andre skal benytte kalenderfunksjon.
Ikke testet på mobil.
> Kalenderkomponenter forside påbegynt

- src/Pages/Hovedside/ManglerKofuviAlert.tsx
- src/Pages/Hovedside/Tjenestebokser/Arbeidsforhold/useAntallArbeidsforholdFraAareg.ts
- src/Pages/Hovedside/Tjenestebokser/Arbeidsplassen/Arbeidsplassen.tsx
- src/Pages/Hovedside/Tjenestebokser/ForebyggeFravær/useSykefravær.ts
- src/Pages/Hovedside/Tjenestebokser/Kandidatlister/useAntallKandidater.ts
- src/Pages/Hovedside/Tjenestebokser/TiltakAvtaler/useAvtaleoversikt.ts
- src/Pages/OmVirksomheten/Kontaktinfo.tsx
- src/Pages/useUserInfo.ts
- src/altinn/tilganger.ts
- src/utils/util.ts
det er regelmessig alerts om disse og det er ikke noe vi kan agere på.
> ikke alert om 502 503 og 504

- src/hooks/useRemoteStorage.ts
Det har kommet et par alerts i sentry på typeerror i value.map hvor "f.map is not a function".
Dette betyr at f er noe annet enn et array, sannsynlivis null eller undefined.
> fix mulig typeerror i lagrefilter value parser

- src/Pages/Saksoversikt/Saksfilter/Virksomhetsmeny/HovedenhetCheckbox.tsx
ref:
instrumentation.ts:28 `checked` is unsupported on <Checkbox> elements within a <CheckboxGroup>. Please set a `value` or `defaultValue` on <CheckboxGroup> instead.
> får en del warnings fra nav-ds som sier at checked ikke skal angis her.

- src/Pages/Hovedside/AktueltRubrikk.tsx
vises fra nå til og med 2024-06-06
> legg til aktualt sak om refusjon av feriepenger

- src/Pages/Saksoversikt/useOversiktStateTransitions.ts
- src/utils/funksjonerForAmplitudeLogging.ts
https://jira.adeo.no/browse/TAG-2251
> TAG-2251: legg til målinger på saksoversikt

- src/Pages/Hovedside/TrengerDuHjelp.css
- src/Pages/Hovedside/TrengerDuHjelp.tsx
> oppdater trenger du hjelp iht ny skisse

- src/Pages/Hovedside/ManglerKontonummerAlert.tsx
ganske sikker på at denne alltid er false. ref: 
* https://github.com/navikt/min-side-arbeidsgiver-api/pull/375
> legg til flagg for om kanendrekontonummer

- server/package-lock.json
- server/package.json
- server/tokenx.js
> bruk oasis for obo tokenx

- src/Pages/Hovedside/InfoBokser.tsx
> ny uxsignals for forebygge fravaer

- src/Pages/useUserInfo.ts
- src/mocks/handlers/userInfoHandler.ts
- src/mocks/scenarios/dagligLederScenario.ts
- src/mocks/scenarios/regnskapsforerScenario.ts
* https://github.com/navikt/min-side-arbeidsgiver-api/pull/380
> flytt "tjenesteid" som konsept til frontend

- package-lock.json
- package.json
- src/Pages/OrganisasjonerOgTilgangerProvider.tsx
- src/utils/amplitude.ts
> Fix amplitude breakage

- src/Pages/Hovedside/InfoBokser.tsx
Tror dette er riktig, trenger bare at noen bekrefter det :)
> endre uxsignals infoboks

- src/GeneriskeElementer/LenkeMedLogging.tsx
- src/Pages/OmVirksomheten/Kontonummer.css
- src/Pages/OmVirksomheten/Kontonummer.tsx
- src/Pages/OmVirksomheten/OverordnetEnhet.tsx
- src/Pages/OmVirksomheten/Underenhet.tsx
- src/api/enhetsregisteretApi.ts
- src/mocks/handlers.ts
- src/mocks/handlers/eregHandlers.ts
- src/mocks/handlers/kontonummerHandler.ts
- src/mocks/msw.ts
- src/mocks/scenarios/dagligLederScenario.ts
- src/mocks/scenarios/nærmesteLederScenario.ts
- src/mocks/scenarios/regnskapsforerScenario.ts
- src/utils/funksjonerForAmplitudeLogging.ts
Legg til visning av kontonummer på "Om virksomheten"
> Kontonummer

- package-lock.json
- package.json
- src/Pages/Banner.tsx
- src/Pages/Pages.tsx
Flyttet NotifikasjoinWidgetProvider inn i egen React Route. La til ApolloProvider da vi ikke får denne globalt fra NotifikasjonWidgetProvider lenger
> Egen side med notifikasjon widget fra pakke
