src/index.tsx, src/mock/altinnBeOmTilgangMock.ts, src/mock/altinnMeldingsboksMock.ts, src/mock/altinnMock.ts, src/mock/enhetsRegisteretMock.ts, src/mock/pamMock.ts, src/mock/syfoMock.ts, src/mock/unleashMock.ts
endre slik at fetchmock ikke evalueres som del av require, men eksplisitt kalles for hver mock.
For å unngå at labs knekker pga dette så har jeg lagt til en linje som eksplisitt mocker altinn. Dette er lik oppførsel som i dag, bare at det ikke skjer som en sideeffekt. Jeg gjorde dette for å unngå breakage da det var forskjell på mocken i frontend og mocken i backend. 
dersom vi tar bort mocking av altinn så må vi også endre backend til å mocke bedriften som fungerer med tiltaksløsningen: https://github.com/navikt/ditt-nav-arbeidsgiver-api/pull/174/files
=> endre slik at fetchmock ikke evalueres som del av require

yarn.lock
via postcss-svgo@4.0.2 -> is-svg@^3.0.0
https://github.com/navikt/ditt-nav-arbeidsgiver/security/dependabot/yarn.lock/is-svg/open
=> bump react-scripts for å fjerne vulnerability

src/utils/funksjonerForAmplitudeLogging.ts
Sektorkode finnes på hovedenhet, ikke underenhet. For nå, bruk bare 84 på næringskode "- Offentlig administrasjon og forsvar, og trygdeordninger underlagt offentlig forvaltning".
=> Logg offentlige

.github/workflows/bygg-branch.yml, .github/workflows/bygg-og-deploy-master.yml
bygg etter merge på fredag feilet pga sentry var nede. Rebuild i dag feilet pga npm cache ikke finnes. 
prøver å få master i vater igjen ved å bumpe til siste setup node action og disable cache
=> bump setup node

src/lenker.ts
https://github.com/navikt/dinesykmeldte
støtter ikke virksomhetsnummer i url enda
=> oppdater lenker til å sende til ny dinesykmeldte app

src/App/OrganisasjonDetaljerProvider.tsx
Nå hentes meldingsboks kun når virksomhet byttes.
Hvis oversikten over meldingsboks-url-er ikke er klar på det tidspunktet,
så blir ikke meldingsboken hentet. Hvis man bytter fram og tilbake mellom
virksomheter, så vil lastingen bli trigget på nytt, og dukker derfor opp.
Skriver om til å bruke en useEffect som merker om prøver å laste
både hvis virksomhet byttes, og hvis listen over meldingsboks-URL-er oppdateres.
=> Fix hent altinn meldingsboks

package-lock.json, package.json, src/App/InformasjonOmBedrift/Tekstboks/Tekstboks.tsx, src/index.tsx
gikk gjennom en og en og fjerne kjørte npm start, testet i browser lokalt og kjørte så npm run build.
Jeg kan ikke se at disse er i bruk, selv ikke polyfillene. 
Da tenker jeg det er bedre å fjerne dem enn å drive å vedlikeholde avhengighetene.
Testet ok:
Oppsummert:
- buffer:
> With [browserify](http://browserify.org/), simply require('buffer') or use the Buffer global and you will get this module.
>
>The goal is to provide an API that is 100% identical to [node's Buffer API](https://nodejs.org/api/buffer.html). Read the [official docs](https://nodejs.org/api/buffer.html) for the full list of properties, instance methods, and class methods that are supported.
- classnames: (var brukt ett sted, endret til en enkel [].join)
- crypto-browserify: (ikke importert noe sted)
> The goal of this …
=> fjern mange ubrukte avhengigheter

server/brukerapi-proxy-middleware.js
Labs er i crashloop, pga manglende env var på labs `TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined `
fra 
```
const createTokenXClient = async () => {
const issuer = await Issuer.discover(TOKEN_X_WELL_KNOWN_URL);
```
=> kun lag tokenXClient dersom audience er angitt

server/brukerapi-proxy-middleware.js, server/server.js
Labs fungerte ikke. Misstenkte det kunne ha med arbeidet med TokenX i backend-en. Flyttet koden som flytter token fra cookie til header ut i en egen middleware som alltid kjøres, uavhengig av om tokenx skjer eller ikke.
=> flytt token fra cookie til header i egen middleware

src/lenker.ts
PS: Vi har satt opp redirects fra min-ia til forebygge-fravar, så brukerne blir ikke påvirket i særlig grad av URL-endringen
=> Endrer til ny URL for "forebygge-fravar" (tidl. "min-ia")

server/server.js
Når denne er ute, kan man endre frontend til å bruke NAIS_CLUSTER_NAME. Så kan vi endre MILJO til å være faktisk miljø.
=> Send NAIS_CLUSTER_NAME from frackend

server/server.js
Frontend no longer uses NAIS_CLUSTER_NAME.
=> Stop sending NAIS_CLUSTER_NAME from frackend

src/App/Hovedside/Sak/SisteSaker/SisteSaker.tsx, src/App/OrganisasjonDetaljerProvider.tsx
Henter antallSaker med useSaker i OrganisasjonDetaljerProvider og sender videre nedover i konteksten. 
Hvis arbeidsgiver er på hovedsiden, og har valgt en virksomhet uten noen saker, vises ikke siste saker. Dersom det likevel finnes saker i en av de andre virksomhetene, vil det stå "Se saker på tvers av alle virksomheter (23)" istedenfor "Se alle saker (23)"
=> Henter antall saker i OrganisasjonDetaljerProvider

README.md, nais/dev-gcp.yaml
Er nok noen problemer med login i hvert fall, men de har skrudd av gamle ingresser nå, så er vel bare å fikse ting etter hvert som vi finner problemer. Og skrive om til Wonderwall.
=> Gamle ingresser i dev skrus av, bruk nye

nais/dev-gcp.yaml, nais/prod-gcp.yaml, server/server.js
kall mot tiltaksgjennomforing-api feiler siden forrige uke. 
anbefales å gå vekk fra apigw
se også
- https://github.com/navikt/tiltak-proxy/pull/28
- https://nav-it.slack.com/archives/CA0AX0Y2V/p1683534573510049
- https://nav-it.slack.com/archives/GULF6A7KL/p1683525687289939
=> bruk tiltak-proxy for kall mot tiltaksgjennomforing

nais/dev-gcp.yaml, nais/labs-gcp.yaml, nais/prod-gcp.yaml, server/mock/antallArbeidsforholdMock.js, server/package-lock.json, server/package.json, server/server.js, src/App/Hovedside/TjenesteBoksContainer/Arbeidsforholdboks/useAntallArbeidsforholdFraAareg.ts
denne må testes i dev, da det er en del breaking changes: https://github.com/chimurai/http-proxy-middleware/blob/master/MIGRATION.md
Har gått gjennom changelog og migration guide, så tror det skal være i orden.
---
=> bump http-proxy-middleware til 3.0.0-beta.1 fro graceful shutdown av proxy

server/server.js
testet lokalt:
```
log.info(`Frackend startup: ${JSON.stringify({ NAIS_CLUSTER_NAME, MILJO, GIT_COMMIT })} 123123123`);
===>
{"level":"info","message":"Frackend startup: {\"NAIS_CLUSTER_NAME\":\"local\",\"MILJO\":\"local\",\"GIT_COMMIT\":\"?\"} *********"}
{"level":"info","message":"main started"}
{"level":"info","message":"Server listening on port 8080"}
```
=> mask format for winston

server/package-lock.json, server/package.json, server/server.js
Vi fortsetter å få 502, og det ser ut som det er i forbindelse med nedskalering. 
Denne PR lener seg på [http-terminator](https://github.com/gajus/http-terminator) for enda litt mer [graceful shutdown](https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-terminating-with-grace). 
Eksempel fra prod hvor vi får [502 når en pod går ned](https://nav-it.slack.com/archives/C04KJL7L545/p1693834185443099):
* https://sentry.gc.nav.no/organizations/nav/issues/501149/?referrer=slack
* https://grafana.nais.io/d/YyfT0144k/team-fager-nginx-ingress?orgId=1&from=1693834105420&to=1693834584665&viewPanel=6
* https://grafana.nais.io/d/bqhN_S8Wz/min-side-ag-dashboard?orgId=1&viewPanel=55&from=1693834076422&to=1693834264399
=> ta i bruk http-terminator for graceful shutdown

server/package-lock.json, server/package.json, server/server.js
vi får noen [HTTP 431](https://sentry.gc.nav.no/organizations/nav/issues/512219/?referrer=slack) som tyder på at vi videresender cookies gjennom proxyen. 
Denne PR legger til en ligen plugin som fjerner cookie header fra alle proxt requests dersom det finnes. 
Fjerner også cookie parser plugin. Den er ikke i bruk.
=> fjern cookie header fra proxy requests

vite.config.ts
ser ut til at noen mener det er nødvendig: https://forum.sentry.io/t/javascript-sourcemap-is-not-used/1012
=> Prøv tilde i source map prefix

server/server.js
Jeg mistenker at grunnen til at vi får så mange gamle klienter, er at vi har default caching med etags på index routen.
Tenker det er verdt et forsøk å sette max-age 1 time på index.html
=> cache index max 1 time

src/App/Alerts/Alerts.tsx, src/App/Hovedside/Sak/useSaker.tsx, src/App/OrganisasjonerOgTilgangerProvider.tsx
AlertProvider brukte den innebygde typen `Set`, som kun kan brukes med mutering. Kopieringen `new Set(...)` for å kompansere for dette var plassert feil. Bytter til `Set` fra immutable-biblioteket så er det umulig™ å gjøre feil.
Endret API-et til å settes ved boolean, siden det virker mer hensiktsmessig med bruken.
=> Fiks mutation-bug i AlertProvider.

src/App/OrganisasjonerOgTilgangerProvider.tsx
Det er ingen som leser `tilgangTilSyfo` fra contexten. Fjerner den.
PS: dette er ikke tilgangen pr. organisasjon, men på tvers av organisasjoner.
=> tilgangTilSyfo i OrganisasjonerOgTilgangerContext brukes ikke

src/App/Hovedside/BeOmTilgang/BeOmTilgang.tsx, src/App/OrganisasjonerOgTilgangerProvider.tsx
Nå kan siden rendre, uten at tilgangssøknader er ferdig lastet.
Det nok åpner opp for refactorings, men har ikke tatt det med i denne PR-en.
=> Flytter altinn tilgangssøknader ut av kritisk path

src/App/LoginBoundary.tsx, src/App/OrganisasjonerOgTilgangerProvider.tsx, src/App/useUserInfo.ts
Spinner ved lasting vises allerede i `LoginBoundary`. Hvis vi ikke får userInfo, så har vi ingen ting å vise, så trenger egentlig ikke noe fallback-verdi.
Ytterligere refactoring følger.
=> useUserInfo uten default value

index.html, nais/dev-gcp.yaml, nais/prod-gcp.yaml
For topnivå-dokuement-kall (~index.html), så returneres 302 med redirect til idporten hvis token er utløpt eller mangler. https://doc.nais.io/addons/wonderwall/#12-autologin
- CSS/JS/osv ligger på cdn, og blir ikke påvirket av dette.
- Vil i praksis kun treffer kallet for index.html
- Ikke erstatning for auth/z.
=> Skru på autologin i wonderwall

server/server.js
Det jeg lånte fra helmetjs/nocache ser ikke ut til å gi mening.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#no-cache
> If you want caches to always check for content updates while reusing stored content, no-cache is the directive to use. It does this by requiring caches to revalidate each request with the origin server.
Note that no-cache does not mean "don't cache". no-cache allows caches to store a response but requires them to revalidate it before reuse. If the sense of "don't cache" that you want is actually "don't store", then no-store is the directive to use.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#no-store
> The no-store response directive indicates that any caches of any kind (private or shared) should not store this …
=> no store cache control og fjern andre konflikterende verdier

index.html
Reverts navikt/min-side-arbeidsgiver#1747
Jeg er litt redd for at redirect-til-login nå er broken. Sliter med å få testet det, men koden gjør en redirect til referrer, så det kan neppe fungere lenger:
```
app.get('/min-side-arbeidsgiver/redirect-til-login', (req, res) => {
const target = new URL(LOGIN_URL);
target.searchParams.set('redirect', req.get('referer'));
res.redirect(target.href);
});
```
=> Revert "set strict-origin referrer policy"

.github/workflows/cicd.yml, package-lock.json, package.json, src/Pages/Saksoversikt/SaksListe.css, vite.config.ts
Det er en del forekomster av feil i prod på at denne mangler.
Endret også litt på struktur i avhengigheter. se https://github.com/navikt/min-side-arbeidsgiver/pull/1781/commits/dadfdd87363b6891f2b3cb04507ffe8646c19f81
=> polyfill string.replaceAll

src/Pages/Saksoversikt/useOversiktSessionStorage.ts
Zod.parse kastet feil i useSessionStateOversikt fordi den parset sessionStorage.route til "/saksoversikt". Dersom dette ikke var url, så kastet den feil. Dette skjer når man går inn i saksoversikten fra forsiden.
=> Sjekker at saksoversikt er i url

src/Pages/Hovedside/Tjenestebokser/Tjenestebokser.tsx, src/altinn/tjenester.ts, src/utils/funksjonerForAmplitudeLogging.ts
Skrev om tilgangskombinasjon slik at den får med alle tjenester. La også til syfo-nærmesteleder.
La til måling av hvilke tjenestebokser som vises til brukeren.
Tilgangskombinasjon var en tekststreng, mulig det er pga noe begrensninger i amplitude.
La til en ny prop ved siden av for å teste ut om vi får til det samme uten å ha de som en tekststreng i kallet til amplitude.
=> legg til måling av tjenestebokser vist og juster tilgangskombinasjon til å omfatte alle tilganger

src/api/storageApi.ts
kan virke som vi av og til får d.map not a function på kall som går etter session er ugyldig. Da vil kallet til backend returnere 401 med en json body, som her blir forsøkt parset
=> litt mer pessmistisk get storage

src/Pages/Hovedside/Tjenestebokser/Tjenestebokser.tsx, src/utils/funksjonerForAmplitudeLogging.ts
ref: https://grafana.nav.cloud.nais.io/d/b70c5556-6d39-44c0-b1ef-ff86c898fdd9/fager-frontend-web-vitals?orgId=1
```
Error - e.toSorted is not a function: stack: Error: e.toSorted is not a function   
at ? (https://cdn.nav.no/fager/min-side-arbeidsgiver/src/Pages/Hovedside/Tjenestebokser/Tjenestebokser.tsx:78:33)   
```
=> toSorted kan ikke brukes i chrome < 109

server/package-lock.json, server/package.json
Bumps the npm_and_yarn group with 2 updates in the /server directory: [path-to-regexp](https://github.com/pillarjs/path-to-regexp) and [express](https://github.com/expressjs/express).
Updates `path-to-regexp` from 0.1.7 to 0.1.10
- [Release notes](https://github.com/pillarjs/path-to-regexp/releases)
- [Changelog](https://github.com/pillarjs/path-to-regexp/blob/master/History.md)
- [Commits](https://github.com/pillarjs/path-to-regexp/compare/v0.1.7...v0.1.10)
Updates `express` from 4.19.2 to 4.20.0
- [Release notes](https://github.com/expressjs/express/releases)
- [Changelog](https://github.com/expressjs/express/blob/master/History.md)
- [Commits](https://github.com/expressjs/express/compare/4.19.2...4.20.0)
---
updated-dependencies:
- dependency-name: path-to-regexp dependency-type: …
=> Bump the npm_and_yarn group across 1 directory with 2 updates

src/Pages/OrganisasjonerOgTilgangerProvider.tsx
uten denne endringen krever det at vi returnerer en liste av alle tilganger fra backend, ikke bare de man har tilgang til.
Med denne endringen så vil vi ikke være avhengig av en liste av alle mulige tilganger fra backend, men lene oss på de frontend bryr seg om å vise.
=> koble tilgangssøknader fra tilganger fra backend

bruker.graphql, package-lock.json, package.json, src/GeneriskeElementer/StatusLinje.tsx, src/Pages/Hovedside/Kalenderavtaler.tsx, src/Pages/Saksoversikt/SakPanel.tsx, src/Pages/Saksoversikt/Saksfilter/Saksfilter.tsx, src/api/graphql-types.ts, src/mocks/brukerApi/alleKalenderavtaler.ts, src/mocks/brukerApi/alleSaker.ts, src/mocks/brukerApi/helpers.ts
lagt til i tidslinje på sak og kommende kalenderavtaler. På kommende kalenderavtaler vil det ikke vises da det filtreres i backend, men koden i frondend støtter det nå uansett. Widget er oppdatert til versjon som støtter avholdt også.
* widget
* tidslinje på sak
* kommende kalenderavtale (denne vil nok aldri egentlig vises pga filtrering i backend)
=> Legg til støtte for kalenderavtale avholdt

package-lock.json, package.json, public/mockServiceWorker.js, src/tests/A11y.test.tsx
Vite har ingen formening om typer i typescript, så vi trenger fortsatt tsc for å validere types. Endringer som er gort:
- Oppdater vite til ny versjon, samt dependencies
- gjøre noen små forbedringer rundt mock service worker
- inkluder type-checking på build. 
- oppdater msw script på bygg
=> Vite update

package-lock.json, package.json, src/Pages/Banner.tsx, src/Pages/OrganisasjonerOgTilgangerContext.ts, src/Pages/OrganisasjonsDetaljerProvider.tsx, src/mocks/handlers/eregHandlers.ts, src/mocks/scenarios/dagligLederScenario.ts
fikser en bug hvor init state på valgtOrganisasjon noen ganger valgte virksomhet man ikke egentlig kan velge. Eks FLI uten parent eller underenheter. For at en virksomhet skal kunne være "velgbar" så må den være en løvnode, mao være en underenhet og ikke selv ha underenheter.
ref tråd i slack: https://nav-it.slack.com/archives/CCNAY9FGF/p1739524896634519
=> fiks init valgt org bug

src/Pages/Saksoversikt/LagreFilter.tsx
Jeg tror dette kan være grunnen til at vi ser noen feil i loggene innimellom. 
Her endrer jeg slik at når man laster et lagret filter så validerer vi at den lagrede verdien er støttet. Dersom den ikke er det fallbackes det til "Nyeste"
=> fiks lagrede filter med verdi som ikke lenger støttes

src/Pages/Hovedside/InfoBokser.tsx, src/Pages/OmVirksomheten/OmVirksomheten.tsx, src/hooks/useCloseInfoboks.ts
trekker derfor ut logikk fra infoboks. Kan legge tilbake senere hvis vi trenger det igjen. ingen visfra-til på nye boksen. Den er der til noen lukker den, eller at vi fjerner koden.
=> etter 1.mai viser vi infoboks til alle som ser på omvirksomheten siden

src/Pages/Hovedside/Tjenestebokser/Sykmeldte/Sykmeldte.tsx
se også:
* https://github.com/navikt/min-side-arbeidsgiver-api/pull/403
Når nærmeste leder ikke har noen sykmeldte så vil det vises slik:
Ellers vises som før:
=> endre visning når antall sykmeldte er 0
